# Settings for the app
app:
  # HTML Title
  title: City of Somerville’s Participatory Budgeting Idea Map
  # Header name
  name: PB Somerville
  # Meta description that will show up in Google search results
  meta_description: _(Submit your ideas for Somerville’s New Participatory Budgeting Process.)
  # Meta author that will show up in Google search results
  meta_author: City of Somerville
  # Social descripiton
  og_description: "_($1,000,000 city budget for your ideas in Somerville. Click here to share what could make our neighborhood even better! #somervillepb)"


  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false

  geocoding_enabled: true
  # The default geocoding engine is MapQuest. You can set an override below.
  # Make sure to provide the appropriate keys for whatever you set.
  geocoding_engine: Mapbox
  geocode_field_label: _(Enter an address...)
  geocode_bounding_box: [42.4188675, -71.1363319, 42.3723418, -71.0711864]  # top, left, bottom, right

  options:
    center:
      lat: 42.3897771
      lng: -71.1027721
    maxBounds:
      - lat: 42.5
        lng: -70.92
      - lat: 42.28
        lng: -71.27
    zoom: 14
    zoomSnap: 0
    minZoom: 12
    maxZoom: 20
    scrollWheelZoom: false
  layers:
    # Raster Tile Layers
    # ==================
    # - url: https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
    #   attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>. Geocoding Courtesy of <a href="http://www.mapquest.com/" target="_blank">MapQuest</a> <img src="http://developer.mapquest.com/content/osm/mq_logo.png">.'

    # Mapbox GL Layers
    # ================
    - type: mapbox
      style: mapbox://styles/poepublic/clf05rgke005h01qgupr9my2s
      accessToken: pk.eyJ1IjoicG9lcHVibGljIiwiYSI6ImNsZTJhaXpjcDA3aHozb21qbm1hdHVvbmUifQ.sLFfLUmV2FFEB5BIZVbE1Q
      attribution: '&copy; <a href="https://www.mapbox.com/about/maps/">Mapbox</a> &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> <strong><a href="https://www.mapbox.com/map-feedback/" target="_blank">Improve this map</a></strong>'
      fallback:
        url: https://api.mapbox.com/styles/v1/poepublic/clf05rgke005h01qgupr9my2s/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoicG9lcHVibGljIiwiYSI6ImNpaDZnYXNxZDBiajlzd20yd2ZwZXhkb3QifQ.XYIHS6tfEXqoiyximdmLXg
        attribution: '&copy; <a href="https://www.mapbox.com/about/maps/">Mapbox</a> &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> <strong><a href="https://www.mapbox.com/map-feedback/" target="_blank">Improve this map</a></strong>'

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  community_resources:
    label: _(Community Resouce Idea)
    rules:
      - condition: '"{{location_type}}" === "community_resources" && {{map.zoom}} < 14 && {{layer.focused}} === false'

        # Display as circles (vectors) when zoomed out
        style:
          radius: 3
          color: '#02187a'
          weight: 1
          opacity: 0.9
          fillColor: '#a379df'
          fillOpacity: 1

      - condition: '"{{location_type}}" === "community_resources" && {{map.zoom}} >= 14 && {{layer.focused}} === false'

        # Display as icons when zoomed in
        icon:
          iconUrl: /static/markers/community_resources-dot.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]

      - condition: '"{{location_type}}" === "community_resources" && {{layer.focused}} === true'

        # Display as markers when focused
        icon:
          iconUrl: /static/markers/community_resources.png
          shadowUrl: /static/markers/shadow.png
          iconSize: [50, 60]
          shadowSize: [58, 25]
          iconAnchor: [25, 60]
          shadowAnchor: [29, 23]

  parks_and_green_space:
    label: _(Parks & Green Space Idea)
    rules:
      - condition: '"{{location_type}}" === "parks_and_green_space" && {{map.zoom}} < 14 && {{layer.focused}} === false'

        # Display as circles (vectors) when zoomed out
        style:
          radius: 3
          color: '#02187a'
          weight: 1
          opacity: 0.9
          fillColor: '#b5df79'
          fillOpacity: 1

      - condition: '"{{location_type}}" === "parks_and_green_space" && {{map.zoom}} >= 14 && {{layer.focused}} === false'

        # Display as icons when zoomed in
        icon:
          iconUrl: /static/markers/parks_and_green_space-dot.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]

      - condition: '"{{location_type}}" === "parks_and_green_space" && {{layer.focused}} === true'

        # Display as markers when focused
        icon:
          iconUrl: /static/markers/parks_and_green_space.png
          shadowUrl: /static/markers/shadow.png
          iconSize: [50, 60]
          shadowSize: [58, 25]
          iconAnchor: [25, 60]
          shadowAnchor: [29, 23]

  streets_and_sidewalks:
    label: _(Streets & Sidewalks Idea)
    rules:
      - condition: '"{{location_type}}" === "streets_and_sidewalks" && {{map.zoom}} < 14 && {{layer.focused}} === false'

        # Display as circles (vectors) when zoomed out
        style:
          radius: 3
          color: '#02187a'
          weight: 1
          opacity: 0.9
          fillColor: '#ffd614'
          fillOpacity: 1

      - condition: '"{{location_type}}" === "streets_and_sidewalks" && {{map.zoom}} >= 14 && {{layer.focused}} === false'

        # Display as icons when zoomed in
        icon:
          iconUrl: /static/markers/streets_and_sidewalks-dot.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]

      - condition: '"{{location_type}}" === "streets_and_sidewalks" && {{layer.focused}} === true'

        # Display as markers when focused
        icon:
          iconUrl: /static/markers/streets_and_sidewalks.png
          shadowUrl: /static/markers/shadow.png
          iconSize: [50, 60]
          shadowSize: [58, 25]
          iconAnchor: [25, 60]
          shadowAnchor: [29, 23]

  arts_and_culture:
    label: _(Arts & Culture Idea)
    rules:
      - condition: '"{{location_type}}" === "arts_and_culture" && {{map.zoom}} < 14 && {{layer.focused}} === false'

        # Display as circles (vectors) when zoomed out
        style:
          radius: 3
          color: '#02187a'
          weight: 1
          opacity: 0.9
          fillColor: '#fa824c'
          fillOpacity: 1

      - condition: '"{{location_type}}" === "arts_and_culture" && {{map.zoom}} >= 14 && {{layer.focused}} === false'

        # Display as icons when zoomed in
        icon:
          iconUrl: /static/markers/arts_and_culture-dot.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]

      - condition: '"{{location_type}}" === "arts_and_culture" && {{layer.focused}} === true'

        # Display as markers when focused
        icon:
          iconUrl: /static/markers/arts_and_culture.png
          shadowUrl: /static/markers/shadow.png
          iconSize: [50, 60]
          shadowSize: [58, 25]
          iconAnchor: [25, 60]
          shadowAnchor: [29, 23]

  education:
    label: _(Education Idea)
    rules:
      - condition: '"{{location_type}}" === "education" && {{map.zoom}} < 14 && {{layer.focused}} === false'

        # Display as circles (vectors) when zoomed out
        style:
          radius: 3
          color: '#02187a'
          weight: 1
          opacity: 0.9
          fillColor: '#3c91e6'
          fillOpacity: 1

      - condition: '"{{location_type}}" === "education" && {{map.zoom}} >= 14 && {{layer.focused}} === false'

        # Display as icons when zoomed in
        icon:
          iconUrl: /static/markers/education-dot.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]

      - condition: '"{{location_type}}" === "education" && {{layer.focused}} === true'

        # Display as markers when focused
        icon:
          iconUrl: /static/markers/education.png
          shadowUrl: /static/markers/shadow.png
          iconSize: [50, 60]
          shadowSize: [58, 25]
          iconAnchor: [25, 60]
          shadowAnchor: [29, 23]

  other_idea:
    label: _(Other Idea)
    rules:
      - condition: '"{{location_type}}" === "other_idea" && {{map.zoom}} < 14 && {{layer.focused}} === false'

        # Display as circles (vectors) when zoomed out
        style:
          radius: 3
          color: '#02187a'
          weight: 1
          opacity: 0.9
          fillColor: '#fafffd'
          fillOpacity: 1

      - condition: '"{{location_type}}" === "other_idea" && {{map.zoom}} >= 14 && {{layer.focused}} === false'

        # Display as icons when zoomed in
        icon:
          iconUrl: /static/markers/other_idea-dot.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]

      - condition: '"{{location_type}}" === "other_idea" && {{layer.focused}} === true'

        # Display as markers when focused
        icon:
          iconUrl: /static/markers/other_idea.png
          shadowUrl: /static/markers/shadow.png
          iconSize: [50, 60]
          shadowSize: [58, 25]
          iconAnchor: [25, 60]
          shadowAnchor: [29, 23]


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported:
    from: '2017-03-07 00:00 -0500'   # Daylight savings begins mid-March
    until: '2099-04-07 00:00 -0400'  # and ends mid-October.
  editors: place-editors
  moderators: place-editors
  response_name: _(place)
  response_plural_name: _(places)
  add_button_label: _(Add a Place)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(List All Places)
  show_map_button_label: _(Show the Map)
  action_text: _(added)
  title: _(Tell us more...)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)

  location_item_name: location
  city_wide_location_label: _(Multiple locations throughout the city)
  unset_location_label: _(Drag the map to set the location.)

  items:
    - prompt: _(Is your idea about a specific location or the entire city?)
      name: city_wide
      sticky: false
      optional: false
      type: radiogroup
      attrs:
        - key: required
          value: true
      options:
      - label: _(A specific location)
        value: no
      - label: _(City-wide)
        value: yes
    - prompt: _(Project Idea)
      type: text
      name: idea
      attrs:
        - key: required
    - prompt: _(Project Category)
      type: radiogroup
      name: location_type
      options:
        - label: _(Community Resources)
          tooltip: _(such as, drinking fountains, public wi-fi, restrooms)
          value: community_resources
        - label: _(Parks & Green Space)
          tooltip: _(such as, play structures, plants and trees, sports equipment)
          value: parks_and_green_space
        - label: _(Streets & Sidewalks)
          tooltip: _(such as, roadway, sidewalk, crosswalk, or lighting improvements)
          value: streets_and_sidewalks
        - label: _(Arts & Culture)
          tooltip: _(such as, public art, cultural events, festivals, city beautification projects)
          value: arts_and_culture
        - label: _(Education)
          tooltip: _(such as, school building improvements, educational programming, enhancing library or school technology and resources)
          value: education
        - label: _(Other)
          tooltip: _(anything else you can think of!)
          value: other_idea
      attrs:
        - key: required
    - prompt: _(Project Location Address)
      type: location
      name: address
      placeholder: _(Drag the map to set the location.)
    - prompt: _(Project Location Name)
      type: text
      name: location_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Location Name)
        - key: size
          value: 30
    - prompt: _(How will this idea improve Somerville?)
      type: textarea
      name: description
      attrs:
        - key: required
    - prompt: _(Give one or two words to describe your project)
      type: text
      name: short_description
      attrs:
        - key: required

    # Contact information...
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      sticky: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - prompt: _(Your Email (will NOT be shown on the map))
      type: text
      name: private-submitter_email
      optional: true
      sticky: true
      attrs:
        - key: placeholder
          value: _(Email address)
        - key: size
          value: 30
    - prompt: _(Check here to join the PB Somerville mailing list to receive updates about the process)
      type: checkbox
      name: private-subscribe
      attrs:
        - key: value
          value: yes

    # Demographic information...
    - prompt: _(What is your gender?)
      name: private-gender
      sticky: true
      optional: true
      type: radiogroup
      options:
        - label: _(Female)
          value: female
        - label: _(Male)
          value: male
        - label: _(Other)
          value: other
          other: true
      attrs:
        - key: data-demographic-info
          value: true
    - prompt: _(What is your age?)
      name: private-age
      sticky: true
      optional: true
      type: number
      attrs:
        - key: min
          value: 0
        - key: max
          value: 99
        - key: data-demographic-info
          value: true
    - prompt: _(What is your race or ethnicity?)
      name: private-race_ethnicity
      sticky: true
      optional: true
      type: radiogroup
      options:
        - label: _(Asian)
          value: asian
        - label: _(Black/African American)
          value: black_african_american
        - label: _(Hispanic/Latino)
          value: hispanic_latino
        - label: _(White)
          value: white
        - label: _(Other)
          value: other
          other: true
      attrs:
        - key: data-demographic-info
          value: true
    - prompt: _(Do you identify as having a disability and/or physical impairment that substantially limits one or more of your major life activities?)
      name: private-disability
      sticky: true
      optional: true
      type: radiogroup
      options:
        - label: _(Yes)
          value: yes
        - label: _(No)
          value: no
      attrs:
        - key: data-demographic-info
          value: true
    - prompt: _(Describe your housing status in Somerville.)
      name: private-housing_status
      sticky: true
      type: radiogroup
      options:
        - label: _(Own)
          value: homeowner
        - label: _(Rent)
          value: renter
        - label: _(Other)
          value: other
          other: true
      attrs:
        - key: data-demographic-info
          value: true


survey:
  submission_type: comments
  adding_supported: true

  # Response config
  show_responses: true
  # Set to true if the user should only submit a survey once
  single_submission: false
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      sticky: true

support:
  submission_type: support
  adding_supported: true
  submit_btn_text: _(Support)
  response_name: _(supporter)
  response_plural_name: _(supporters)
  action_text: _(supported)
  anonymous_name: _(Someone)

pages:
  - title: _(Overview)
    slug: overview
    url: /static/pages/overview.html
    start_page: true

  - title: _(Filter Ideas)
    slug: filter-type
    pages:
      - title: _(All Ideas)
        external: true
        url: /filter/all
      - title: _(Community Resources)
        url: /filter/community_resources
        external: true
      - title: _(Parks & Green Space)
        url: /filter/parks_and_green_space
        external: true
      - title: _(Streets & Sidewalks)
        url: /filter/streets_and_sidewalks
        external: true
      - title: _(Arts & Culture)
        url: /filter/arts_and_culture
        external: true
      - title: _(Education)
        url: /filter/education
        external: true
      - title: _(Other)
        url: /filter/other_idea
        external: true

notifications:
  on_new_place: true
  submitter_email_field: private-submitter_email
