# Settings for the app
app:
  # HTML Title
  title: City of Somerville’s Participatory Budgeting Idea Map
  # Header name
  name: PB Somerville
  # Meta description that will show up in Google search results
  meta_description: _(Submit your ideas for Somerville’s First-Ever Participatory Budgeting initiative.)
  # Meta author that will show up in Google search results
  meta_author: City of Somerville


  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false

  geocoding_enabled: true
  # The default geocoding engine is MapQuest. You can set an override below.
  # Make sure to provide the appropriate keys for whatever you set.
  geocoding_engine: Mapbox
  geocode_field_label: _(Enter an address...)
  geocode_bounding_box: [42.4188675, -71.1363319, 42.3723418, -71.0711864]  # top, left, bottom, right

  options:
    center:
      lat: 42.3897771
      lng: -71.1027721
    maxBounds:
      - lat: 42.5
        lng: -70.92
      - lat: 42.28
        lng: -71.27
    zoom: 14
    zoomSnap: 0
    minZoom: 12
    maxZoom: 18
    scrollWheelZoom: false
  layers:
    # Raster Tile Layers
    # ==================
    # - url: https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
    #   attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>. Geocoding Courtesy of <a href="http://www.mapquest.com/" target="_blank">MapQuest</a> <img src="http://developer.mapquest.com/content/osm/mq_logo.png">.'

    # Mapbox GL Layers
    # ================
    - type: mapbox
      style: mapbox://styles/poepublic/clcrcb2ne000914p9vcpgs9oz
      accessToken: pk.eyJ1IjoicG9lcHVibGljIiwiYSI6ImNsZTJhaXpjcDA3aHozb21qbm1hdHVvbmUifQ.sLFfLUmV2FFEB5BIZVbE1Q
      attribution: '&copy; <a href="https://www.mapbox.com/about/maps/">Mapbox</a> &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> <strong><a href="https://www.mapbox.com/map-feedback/" target="_blank">Improve this map</a></strong>'
      fallback:
        url: https://api.mapbox.com/styles/v1/poepublic/clcrcb2ne000914p9vcpgs9oz/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoicG9lcHVibGljIiwiYSI6ImNpaDZnYXNxZDBiajlzd20yd2ZwZXhkb3QifQ.XYIHS6tfEXqoiyximdmLXg
        attribution: '&copy; <a href="https://www.mapbox.com/about/maps/">Mapbox</a> &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> <strong><a href="https://www.mapbox.com/map-feedback/" target="_blank">Improve this map</a></strong>'

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  parks_and_green_space:
    label: _(Parks & Green Space)
    rules:
      - condition: '"{{location_type}}" === "parks_and_green_space" && {{map.zoom}} < 14 && {{layer.focused}} === false'

        # Display as circles (vectors) when zoomed out
        style:
          radius: 3
          color: '#02187a'
          weight: 1
          opacity: 0.9
          fillColor: '#b5df79'
          fillOpacity: 1

      - condition: '"{{location_type}}" === "parks_and_green_space" && {{map.zoom}} >= 14 && {{layer.focused}} === false'

        # Display as icons when zoomed in
        icon:
          iconUrl: /static/markers/parks_and_green_space-dot.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]

      - condition: '"{{location_type}}" === "parks_and_green_space" && {{layer.focused}} === true'

        # Display as markers when focused
        icon:
          iconUrl: /static/markers/parks_and_green_space.png
          shadowUrl: /static/markers/shadow.png
          iconSize: [50, 60]
          shadowSize: [58, 25]
          iconAnchor: [25, 60]
          shadowAnchor: [29, 23]

  streets_and_sidewalks:
    label: _(Streets & Sidewalks)
    rules:
      - condition: '"{{location_type}}" === "streets_and_sidewalks" && {{map.zoom}} < 14 && {{layer.focused}} === false'

        # Display as circles (vectors) when zoomed out
        style:
          radius: 3
          color: '#02187a'
          weight: 1
          opacity: 0.9
          fillColor: '#ffd614'
          fillOpacity: 1

      - condition: '"{{location_type}}" === "streets_and_sidewalks" && {{map.zoom}} >= 14 && {{layer.focused}} === false'

        # Display as icons when zoomed in
        icon:
          iconUrl: /static/markers/streets_and_sidewalks-dot.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]

      - condition: '"{{location_type}}" === "streets_and_sidewalks" && {{layer.focused}} === true'

        # Display as markers when focused
        icon:
          iconUrl: /static/markers/streets_and_sidewalks.png
          shadowUrl: /static/markers/shadow.png
          iconSize: [50, 60]
          shadowSize: [58, 25]
          iconAnchor: [25, 60]
          shadowAnchor: [29, 23]

  arts_and_culture:
    label: _(Arts & Culture)
    rules:
      - condition: '"{{location_type}}" === "arts_and_culture" && {{map.zoom}} < 14 && {{layer.focused}} === false'

        # Display as circles (vectors) when zoomed out
        style:
          radius: 3
          color: '#02187a'
          weight: 1
          opacity: 0.9
          fillColor: '#fa824c'
          fillOpacity: 1

      - condition: '"{{location_type}}" === "arts_and_culture" && {{map.zoom}} >= 14 && {{layer.focused}} === false'

        # Display as icons when zoomed in
        icon:
          iconUrl: /static/markers/arts_and_culture-dot.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]

      - condition: '"{{location_type}}" === "arts_and_culture" && {{layer.focused}} === true'

        # Display as markers when focused
        icon:
          iconUrl: /static/markers/arts_and_culture.png
          shadowUrl: /static/markers/shadow.png
          iconSize: [50, 60]
          shadowSize: [58, 25]
          iconAnchor: [25, 60]
          shadowAnchor: [29, 23]

  education:
    label: _(Education)
    rules:
      - condition: '"{{location_type}}" === "education" && {{map.zoom}} < 14 && {{layer.focused}} === false'

        # Display as circles (vectors) when zoomed out
        style:
          radius: 3
          color: '#02187a'
          weight: 1
          opacity: 0.9
          fillColor: '#3c91e6'
          fillOpacity: 1

      - condition: '"{{location_type}}" === "education" && {{map.zoom}} >= 14 && {{layer.focused}} === false'

        # Display as icons when zoomed in
        icon:
          iconUrl: /static/markers/education-dot.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]

      - condition: '"{{location_type}}" === "education" && {{layer.focused}} === true'

        # Display as markers when focused
        icon:
          iconUrl: /static/markers/education.png
          shadowUrl: /static/markers/shadow.png
          iconSize: [50, 60]
          shadowSize: [58, 25]
          iconAnchor: [25, 60]
          shadowAnchor: [29, 23]

  other_idea:
    label: _(Other)
    rules:
      - condition: '"{{location_type}}" === "other_idea" && {{map.zoom}} < 14 && {{layer.focused}} === false'

        # Display as circles (vectors) when zoomed out
        style:
          radius: 3
          color: '#02187a'
          weight: 1
          opacity: 0.9
          fillColor: '#fafffd'
          fillOpacity: 1

      - condition: '"{{location_type}}" === "other_idea" && {{map.zoom}} >= 14 && {{layer.focused}} === false'

        # Display as icons when zoomed in
        icon:
          iconUrl: /static/markers/other_idea-dot.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]

      - condition: '"{{location_type}}" === "other_idea" && {{layer.focused}} === true'

        # Display as markers when focused
        icon:
          iconUrl: /static/markers/other_idea.png
          shadowUrl: /static/markers/shadow.png
          iconSize: [50, 60]
          shadowSize: [58, 25]
          iconAnchor: [25, 60]
          shadowAnchor: [29, 23]


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported:
    from: '2017-03-07 00:00 -0500'   # Daylight savings begins mid-March
    until: '2099-04-07 00:00 -0400'  # and ends mid-October.
  editors: place-editors
  moderators: place-editors
  response_name: _(place)
  response_plural_name: _(places)
  add_button_label: _(Add a Place)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(List All Places)
  show_map_button_label: _(Show the Map)
  action_text: _(added)
  title: _(Tell us more...)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)

  location_item_name: location

  items:
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      sticky: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - prompt: _(Your Email)
      type: text
      name: private-submitter_email
      optional: true
      sticky: true
      attrs:
        - key: placeholder
          value: _(Email address)
        - key: size
          value: 30
    - prompt: _(Project Idea)
      type: text
      name: idea
      attrs:
        - key: required
    - prompt: _(Project Category)
      type: radiogroup
      name: location_type
      options:
        - label: _(Parks & Green Space)
          value: parks_and_green_space
        - label: _(Streets & Sidewalks)
          value: streets_and_sidewalks
        - label: _(Arts & Culture)
          value: arts_and_culture
        - label: _(Education)
          value: education
        - label: _(Other)
          value: other_idea
      attrs:
        - key: required
    - prompt: _(Give one or two words to describe your project)
      type: text
      name: short_description
      attrs:
        - key: required
    - prompt: _(Project Location Address)
      type: location
      name: address
      placeholder: _(Drag the map to set the location.)
    - prompt: _(Project Location Name)
      type: text
      name: location_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Location Name)
        - key: size
          value: 30
    - prompt: _(How will this idea improve Somerville?)
      type: textarea
      name: description
      attrs:
        - key: required

survey:
  submission_type: comments
  adding_supported: true

  # Response config
  show_responses: true
  # Set to true if the user should only submit a survey once
  single_submission: false
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Yes or no question)
      type: radiogroup
      options:
        - label: _(Indeed)
          value: yeah
        - label: _(I don't think so)
          value: nah
      name: y_or_n
      attrs:
        - key: required
    - prompt: _(All that apply questiion)
      type: checkboxgroup
      options:
        - label: _(First)
          value: option1
        - label: _(Second)
          value: option2
        - label: _(Third)
          value: option3
        - label: _(Fourth)
          value: option4
      name: all_that_apply
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      sticky: true

support:
  submission_type: support
  adding_supported: true
  submit_btn_text: _(Support)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(Overview)
    slug: overview
    url: /static/pages/overview.html
    start_page: true

  - title: Filter Places
    slug: filter-type
    pages:
      - title: All
        external: true
        url: /filter/all
      - title: _(Parks & Green Space)
        url: /filter/parks_and_green_space
        external: true
      - title: _(Streets & Sidewalks)
        url: /filter/streets_and_sidewalks
        external: true
      - title: _(Arts & Culture)
        url: /filter/arts_and_culture
        external: true
      - title: _(Education)
        url: /filter/education
        external: true
      - title: _(Other)
        url: /filter/other_idea
        external: true

notifications:
  on_new_place: true
  submitter_email_field: private-submitter_email
